version: '3.9'

services:
  postgres:
    container_name: pg-ru
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
