version: '3.9'

services:

  postgres:
    container_name: pg-ru
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped


  pinger:
    build:
      context: ./pinger-app
      dockerfile: Dockerfile
    image: postgres-pinger:0.1
    container_name: pinger
    depends_on:
      - postgres
    env_file:
      - ./pinger-app/.env.pinger
    volumes:
      - ./pinger-logs:/var/log
    restart: unless-stopped


  sdl-app:
    build:
      context: ./sdl-app
      dockerfile: Dockerfile
    container_name: sdl-app
    depends_on:
      - postgres
    environment:
      LOG_DUPLICATE_PATH: /logs/sdl.log
    volumes:
      - ./sdl-logs:/logs
    stdin_open: true
    tty: true
    restart: unless-stopped
